apiVersion: apps/v1
kind: Deployment
metadata:
  name: treino-rails
  labels:
    app: treino-rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treino-rails
  template:
    metadata:
      labels:
        app: treino-rails
    spec:
      initContainers:
        - name: db-migrate
          image: todo-app-v1:latest
          command: ["./bin/rails", "db:prepare"]
          env:
            # Chave 'uri' gerada automaticamente pelo CNPG no Secret
            # treino-postgres-app: postgresql://user:pass@host:port/db
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: treino-postgres-app
                  key: uri
            - name: SECRET_KEY_BASE
              value: "treino-nao-use-em-producao-0123456789abcdef"
      containers:
        - name: api
          image: todo-app-v1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: treino-postgres-app
                  key: uri
            - name: SECRET_KEY_BASE
              value: "treino-nao-use-em-producao-0123456789abcdef"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /up
              port: http
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /up
              port: http
            failureThreshold: 3
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /up
              port: http
            failureThreshold: 18
            periodSeconds: 10
